version: "3.8"

services:
  database: 
    image: mysql:latest
    container_name: database-app 
    restart: always 
    build: 
      context: ./sql
      dockerfile: ../docker/mysql/Dockerfile
    ports: 
      - "3306:3306"
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=healthy_idaho_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

  backend:
    container_name: backend-app
    restart: always
    build:
      context: ./backend
      dockerfile: ../docker/django/Dockerfile
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=healthy_idaho_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "8001:8000"
    depends_on:
      - database
    links: 
      - database
    networks:
      - hh-net

  frontend:
    container_name: frontend-app
    restart: always
    build:
      context: ./frontend
      dockerfile: ../docker/react/Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - hh-net
networks:
  hh-net:
    driver: bridge
