CREATE TABLE HEALTHY_IDAHO(
    COUNTY          CHAR(11) NOT NULL
    ,FIPS           BIGINT NOT NULL PRIMARY KEY
    ,MINSTATLANG    DECIMAL(5, 4)
    ,OVERVULN       DECIMAL(5, 4)
    ,TYPETRANS      DECIMAL(5, 4)
    ,COMPDIS        DECIMAL(5, 4)
    ,SOCIOECO       DECIMAL(5, 4)
    ,GREEN          DECIMAL(18, 16)
    ,HEATISLAND     DECIMAL(20, 19)
    ,LST_MAX        DECIMAL(20, 18)
    ,LST_MEAN       DECIMAL(20, 18)
    ,SMOKE          DECIMAL(20, 15)
    ,POPULAT        INT(5)
    ,PM25           DECIMAL(20, 15)
);
CREATE INDEX COUNTY_ID
    ON HEALTHY_IDAHO(FIPS);