name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Prereq script
        run: ./prereq.sh
      - name: Run build script
        run: ./build.sh
      - name: Run test script
        run: ./test.sh
