name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running Prerequisites
        run: ./prereq.sh
      - name: Run Building Project
        run: ./build.sh
